site_name: 'Pheno-Ranker Documentation'
site_description: 'Pheno-Ranker Documentation'
site_author: 'Manuel Rueda, PhD'
copyright: '&copy; Copyright 2023, Manuel Rueda, CNAG'
repo_name: 'Pheno-Ranker'
repo_url: https://github.com/mrueda/pheno-ranker
edit_uri: edit/main/docs/

extra_css: [css/theme_overrides.css]
extra_javascript: [js/theme_overrides.js]

plugins:
  - search
  - macros
  - mermaid2:
      arguments:
        startOnLoad: true

markdown_extensions:
    - toc:
        toc_depth: 2-3
        permalink: true
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.saneheaders
    - pymdownx.magiclink:
        hide_protocol: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - mdx_gh_links:
        user: CNAG-Biomedical-Informatics
        repo: pheno-ranker
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid
    - pymdownx.snippets:
        base_path: docs
        url_download: true

nav:
  - Introduction:
      - What is Pheno-Ranker?: what-is-pheno-ranker.md
      - Which are the supported formats:
          - BFF: bff.md
          - PXF: pxf.md
          - Other formats: other-formats.md
  - 'Download & Installation': download-and-installation.md
  - Web App User interface: https://pheno-ranker.cnag.eu
  - Modes of operation:
      - Cohort mode: cohort.md 
      - Patient mode: patient.md
  - Utilities:
      - BFF/PXF simulator: simulator.md 
      - CSV import: csv-import.md
  - Technical details:
      - Implementation: implementation.md
#      - Algorithm: algorithm.md
#      - Federated version: federated-version.md
  - Help:
      - Tutorial: tutorial.md
      - Google colab: https://colab.research.google.com/drive/1n3Etu4fnwuDWNveSMb1SzuN50O2a05Rg#scrollTo=8tbJ0f5-hJAB
      - Usage: usage.md
      - FAQs: faq.md
      - 'Addendum: openEHR': addendum-open-ehr.md
  - About:
      - About: about.md
      - Citation: citation.md

theme:
  name: material
  #custom_dir: overrides
  palette:
  - media: '(prefers-color-scheme: dark)'
    scheme: default
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  logo: img/iconhex.svg
  favicon: img/favicon-2x.png
  icon:
      repo: fontawesome/brands/github-alt 
  features:
        - content.tabs.link
        - search.highlight
        - search.share
        # - navigation.instant # otherwise blocks rendering of mermaid on page load
        - navigation.tracking
        - navigation.sections
        - toc.integrate

# Options
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/mrueda
