#!/usr/bin/env python3
#
#   A script that creates an image with stats for BFF|PXF
#
#   Last Modified: Jan/17/2023
#
#   Version 0.04
#
#   Copyright (C) 2023-2024 Manuel Rueda - CNAG (manuel.rueda@cnag.eu)
#
#   License: Artistic License 2.0
#
#   If this program helps you in your research, please cite.

import bff_pxf_plot_utils

if __name__ == "__main__":
    bff_pxf_plot_utils.main_generate()
