package Ontologies;

use strict;
use warnings;
use Exporter 'import';
our @EXPORT_OK = qw( $hpo_array $omim_array $rxnorm_array $ethnicity_array);

# GPT-4
our $hpo_array = [
    { id => 'HP:0001250', label => 'Seizure' },
    { id => 'HP:0001263', label => 'Global developmental delay' },
    { id => 'HP:0004322', label => 'Short stature' },
    { id => 'HP:0000505', label => 'Myopia' },
    { id => 'HP:0001510', label => 'Growth abnormality' },
    { id => 'HP:0001518', label => 'Small for gestational age' },
    { id => 'HP:0001537', label => 'Wide nasal bridge' },
    { id => 'HP:0002015', label => 'Dysphagia' },
    { id => 'HP:0002023', label => 'Megacolon' },
    { id => 'HP:0002353', label => 'Seizures' },
    { id => 'HP:0004325', label => 'Decreased body weight' },
    { id => 'HP:0009778', label => 'Long philtrum' },
    { id => 'HP:0010628', label => 'Delayed gross motor development' },
    { id => 'HP:0012469', label => 'Cleft upper lip' },
    { id => 'HP:0100543', label => 'Cognitive impairment' },
    { id => 'HP:0100716', label => 'Gait disturbance' },
    { id => 'HP:0000407', label => 'Sensorineural hearing impairment' },
    { id => 'HP:0000819', label => 'Diabetes mellitus' },
    { id => 'HP:0001000', label => 'Hypopigmented skin patches' },
    { id => 'HP:0001249', label => 'Intellectual disability' },
    { id => 'HP:0001508', label => 'Failure to thrive' },
    { id => 'HP:0001513', label => 'Intrauterine growth retardation' },
    { id => 'HP:0002007', label => 'Frontal bossing' },
    { id => 'HP:0002017', label => 'Gastroesophageal reflux' },
    { id => 'HP:0002031', label => 'Constipation' },
    { id => 'HP:0002354', label => 'Generalized tonic-clonic seizures' },
    { id => 'HP:0004326', label => 'Increased body weight' },
    { id => 'HP:0009878', label => 'Micrognathia' },
    { id => 'HP:0010629', label => 'Delayed fine motor development' },
    { id => 'HP:0012470', label => 'Cleft lower lip' },
    { id => 'HP:0100544', label => 'Language impairment' },
    {
        id    => 'HP:0100717',
        label => 'Abnormality of extrapyramidal motor function'
    },
    { id => 'HP:0000408', label => 'Mixed hearing impairment' },
    { id => 'HP:0000821', label => 'Type I diabetes mellitus' },
    { id => 'HP:0001001', label => 'Cafe-au-lait spot' },
    { id => 'HP:0001252', label => 'Muscular hypotonia' },
    { id => 'HP:0001509', label => 'Growth delay' },
    { id => 'HP:0001520', label => 'Large for gestational age' },
    { id => 'HP:0002008', label => 'High forehead' },
    { id => 'HP:0002018', label => 'Recurrent gastroesophageal reflux' },
    { id => 'HP:0002032', label => 'Diarrhea' },
    { id => 'HP:0002355', label => 'Febrile seizures' },
    { id => 'HP:0004327', label => 'Decreased body mass index' },
    { id => 'HP:0009880', label => 'Retrognathia' },
    { id => 'HP:0010630', label => 'Delayed speech and language development' },
    { id => 'HP:0012471', label => 'Cleft palate' },
    { id => 'HP:0100545', label => 'Memory impairment' },
    { id => 'HP:0100718', label => 'Abnormality of the substantia nigra' },
    {
        id    => 'HP:0500225',
        label => 'CSF serine family amino acid concentration'
    },
    { id => 'HP:5200036', label => 'Lack of response to verbal cues' }
];

# GPT-4
our $omim_array = [
    { id => 'OMIM:100100', label => 'Aarskog-Scott Syndrome' },
    { id => 'OMIM:100200', label => 'Achondroplasia' },
    { id => 'OMIM:100300', label => 'Adenosine Deaminase Deficiency' },
    { id => 'OMIM:100400', label => 'Adrenoleukodystrophy' },
    { id => 'OMIM:100500', label => 'Albinism' },
    { id => 'OMIM:100600', label => 'Alkaptonuria' },
    { id => 'OMIM:100700', label => 'Amyloidosis' },
    { id => 'OMIM:100800', label => 'Aniridia' },
    { id => 'OMIM:100900', label => 'Antithrombin III Deficiency' },
    { id => 'OMIM:101000', label => 'Apolipoprotein A-I Deficiency' },
    { id => 'OMIM:101100', label => 'Arginase Deficiency' },
    { id => 'OMIM:101200', label => 'Arthrogryposis Multiplex Congenita' },
    { id => 'OMIM:101300', label => 'Aspartylglucosaminuria' },
    { id => 'OMIM:101400', label => 'Ataxia-Telangiectasia' },
    { id => 'OMIM:101500', label => 'Autosomal Dominant Polycystic Kidney Disease' },
    { id => 'OMIM:101600', label => 'Bardet-Biedl Syndrome' },
    { id => 'OMIM:101700', label => 'Batten Disease' },
    { id => 'OMIM:101800', label => 'Becker Muscular Dystrophy' },
    { id => 'OMIM:101900', label => 'Berardinelli-Seip Congenital Lipodystrophy' },
    { id => 'OMIM:102000', label => 'Beta-Mannosidosis' },
    { id => 'OMIM:102100', label => 'Beta-Thalassemia' },
    { id => 'OMIM:102200', label => 'Biotinidase Deficiency' },
    { id => 'OMIM:102300', label => 'Bloom Syndrome' },
    { id => 'OMIM:102400', label => 'Canavan Disease' },
    { id => 'OMIM:102500', label => 'Carnitine Palmitoyltransferase II Deficiency' },
    { id => 'OMIM:102600', label => 'Celiac Disease' },
    { id => 'OMIM:102700', label => 'Charcot-Marie-Tooth Disease' },
    { id => 'OMIM:102800', label => 'Chediak-Higashi Syndrome' },
    { id => 'OMIM:102900', label => 'Choroideremia' },
    { id => 'OMIM:103000', label => 'Citrullinemia' },
    { id => 'OMIM:103100', label => 'Cockayne Syndrome' },
    { id => 'OMIM:103200', label => 'Congenital Adrenal Hyperplasia' },
    { id => 'OMIM:103300', label => 'Hypoglossia-hypodactyly'},
    { id => 'OMIM:103400', label => 'Congenital Disorder of Glycosylation' },
    { id => 'OMIM:103500', label => 'Crigler-Najjar Syndrome' },
    { id => 'OMIM:103600', label => 'Cystic Fibrosis' },
    { id => 'OMIM:103700', label => 'Cystinosis' },
    { id => 'OMIM:103800', label => 'Danon Disease' },
    { id => 'OMIM:103900', label => 'Dent Disease' },
    { id => 'OMIM:104000', label => 'Dermatomyositis' },
    { id => 'OMIM:104100', label => 'Diamond-Blackfan Anemia' },
    { id => 'OMIM:104200', label => 'Dravet Syndrome' },
    { id => 'OMIM:104300', label => 'Duchenne Muscular Dystrophy' },
    { id => 'OMIM:104400', label => 'Ehlers-Danlos Syndrome' },
    { id => 'OMIM:104500', label => 'Fabry Disease' },
    { id => 'OMIM:104600', label => 'Familial Mediterranean Fever' },
    { id => 'OMIM:104700', label => 'Fanconi Anemia' },
    { id => 'OMIM:104800', label => 'Fragile X Syndrome' },
    { id => 'OMIM:104900', label => 'Frederick Ataxia' },
    { id => 'OMIM:105000', label => 'Fucosidosis' },
];

our $rxnorm_array = [
    { id => 'RxNorm:10582', label => 'Acetaminophen' },
    { id => 'RxNorm:435',   label => 'Albuterol' },
    { id => 'RxNorm:5640',  label => 'Amoxicillin' },
    { id => 'RxNorm:2130',  label => 'Amlodipine' },
    { id => 'RxNorm:703',   label => 'Aspirin' },
    { id => 'RxNorm:1191',  label => 'Atorvastatin' },
    { id => 'RxNorm:3322',  label => 'Citalopram' },
    { id => 'RxNorm:2670',  label => 'Clopidogrel' },
    { id => 'RxNorm:8640',  label => 'Doxycycline' },
    { id => 'RxNorm:3289',  label => 'Escitalopram' },
    { id => 'RxNorm:1978',  label => 'Furosemide' },
    { id => 'RxNorm:284',   label => 'Gabapentin' },
    { id => 'RxNorm:4826',  label => 'Hydrochlorothiazide' },
    { id => 'RxNorm:6170',  label => 'Ibuprofen' },
    { id => 'RxNorm:688',   label => 'Levothyroxine' },
    { id => 'RxNorm:5244',  label => 'Lisinopril' },
    { id => 'RxNorm:5362',  label => 'Lorazepam' },
    { id => 'RxNorm:6717',  label => 'Losartan' },
    { id => 'RxNorm:6809',  label => 'Lovastatin' },
    { id => 'RxNorm:7242',  label => 'Metformin' },
    { id => 'RxNorm:7432',  label => 'Metoprolol' },
    { id => 'RxNorm:2022',  label => 'Montelukast' },
    { id => 'RxNorm:7986',  label => 'Naproxen' },
    { id => 'RxNorm:8732',  label => 'Omeprazole' },
    { id => 'RxNorm:8896',  label => 'Oxycodone' },
    { id => 'RxNorm:9156',  label => 'Paroxetine' },
    { id => 'RxNorm:7799',  label => 'Prednisone' },
    { id => 'RxNorm:9496',  label => 'Propranolol' },
    { id => 'RxNorm:9792',  label => 'Ranitidine' },
    { id => 'RxNorm:10418', label => 'Sertraline' },
    { id => 'RxNorm:10438', label => 'Simvastatin' },
    { id => 'RxNorm:10506', label => 'Tamsulosin' },
    { id => 'RxNorm:10689', label => 'Tramadol' },
    { id => 'RxNorm:10852', label => 'Trazodone' },
    { id => 'RxNorm:11289', label => 'Valsartan' },
    { id => 'RxNorm:11372', label => 'Venlafaxine' },
    { id => 'RxNorm:11402', label => 'Verapamil' },
    { id => 'RxNorm:11517', label => 'Warfarin' },
    { id => 'RxNorm:11974', label => 'Zolpidem' },
    { id => 'RxNorm:10456', label => 'Ciprofloxacin' },
    { id => 'RxNorm:10958', label => 'Fluoxetine' },
    { id => 'RxNorm:1202',  label => 'Azithromycin' },
    { id => 'RxNorm:150840', label => 'Duloxetine' },
    { id => 'RxNorm:2162',  label => 'Clonazepam' },
    { id => 'RxNorm:4059',  label => 'Enalapril' },
    { id => 'RxNorm:26225', label => 'Lansoprazole' },
    { id => 'RxNorm:5966',  label => 'Spironolactone' },
    { id => 'RxNorm:7582',  label => 'Pantoprazole' },
    { id => 'RxNorm:7846',  label => 'Pravastatin' },
    { id => 'RxNorm:9062',  label => 'Olanzapine' },
    { id => 'RxNorm:10178', label => 'Sildenafil' },
    { id => 'RxNorm:10273', label => 'Sumatriptan' },
    { id => 'RxNorm:10631', label => 'Topiramate' }
];

# mrueda (GPT-4 hallucinated on this one)
our $ethnicity_array = [
    { id => 'NCIT:C42331', label => 'African' },
    { id => 'NCIT:C67109', label => 'Any other Asian background' },
    { id => 'NCIT:C67109', label => 'Any other Black background' },
    { id => 'NCIT:C67109', label => 'Any other mixed background' },
    { id => 'NCIT:C67109', label => 'Any other white background' },
    { id => 'NCIT:C41260', label => 'Asian or Asian British' },
    { id => 'NCIT:C41260', label => 'Bangladeshi' },
    { id => 'NCIT:C16352', label => 'Black or Black British' },
    { id => 'NCIT:C41261', label => 'British' },
    { id => 'NCIT:C77810', label => 'Caribbean' },
    { id => 'NCIT:C41260', label => 'Chinese' },
    { id => 'NCIT:C67109', label => 'Indian' },
    { id => 'NCIT:C43856', label => 'Irish' },
    { id => 'NCIT:C67109', label => 'Mixed' },
    { id => 'NCIT:C67109', label => 'Other ethnic group' },
    { id => 'NCIT:C41260', label => 'Pakistani' },
    { id => 'NCIT:C41261', label => 'White' },
    { id => 'NCIT:C67109', label => 'White and Asian' },
    { id => 'NCIT:C67109', label => 'White and Black African' },
    { id => 'NCIT:C67109', label => 'White and Black Caribbean' }
];
1;
