#!/usr/bin/env python3
#
#   A script that creates 2D-barcodes(QR) from Pheno-Ranker export data
#
#   Last Modified: Dec/01/2023
#
#   Version 0.08
#
#   Copyright (C) 2023 Manuel Rueda - CNAG (manuel.rueda@cnag.eu)
#
#   License: Artistic License 2.0
#
#   If this program helps you in your research, please cite.

import qr_code_utils

if __name__ == "__main__":
    qr_code_utils.main_generate()
