---
# Set the number of cohort-patient comparison print to STDOUT
max_out: 50

# Set the key for sorting
sort_by: hamming

# Set the primary key for the objects
primary_key: id

# Set the allowed terms / properties
allowed_terms: [biosamples,diseases,ethnicity,exposures,files,geographicOrigin,id,info,interpretations,interventionsOrProcedures,karyotypicSex,measurements,measures,medicalActions,metaData,pedigrees,phenotypicFeatures,sex,subject,treatments]

# Set the maximum numbers to variables to be used (if more they will randomized)
max_number_var: 10000

# Set the seed number to initialize a pseudorandom number generator for max_number_var:
seed: 123456789 

# Set the regex to discard variables that contain a given patter
exclude_properties_regex: 'info|notes|label|value|\.high|\.low|metaData|familyHistory|excluded|_visit|dateOfProcedure'

# Set the regex to perform the subsitition of array elements for
#array_terms: [measures,treatments,exposures,diseases,phenotypicFeatures,interventionsOrProcedures,medicalActions]
#array_regex: '^(\w+):(\d+)\.(\S+)'
