---
# Set the number of cohort-patient comparison print to STDOUT
max_out: 50

# Set the key for sorting
sort_by: hamming

# Set the primary key for the objects
primary_key: id

# Set the allowed terms / properties
allowed_terms: [biosamples,diseases,ethnicity,exposures,files,geographicOrigin,id,info,interpretations,interventionsOrProcedures,karyotypicSex,measurements,measures,medicalActions,metaData,pedigrees,phenotypicFeatures,sex,subject,treatments]

# Set the maximum numbers to variables to be used (if more they will randomized)
max_number_var: 10000

# Set the seed number to initialize a pseudorandom number generator for max_number_var:
seed: 123456789 

# Set the regex to discard variables that contain a given patter
exclude_properties_regex: 'info|notes|label|value|\.high|\.low|metaData|familyHistory|excluded|_visit|dateOfProcedure'

# Set the path for array properties
id_correspondence:
  BFF:
    measures: 'assayCode.id'
    treatments: 'treatmentCode.id'
    exposures: 'exposureCode.id'
    diseases: 'diseaseCode.id'
    phenotypicFeatures: 'featureType.id'
    interventionsOrProcedures: 'procedureCode.id'
  PXF:
    medicalActions: 'treatment.agent.id'
    diseases: 'term.id'
    phenotypicFeatures: 'type.id'
    # measures                  => 'assayCode.id',
    # exposures                 => 'exposureCode.id',
    # interventionsOrProcedures => 'procedureCode.id'

# Set the terms which are arrays
array_terms: [measures,treatments,exposures,diseases,phenotypicFeatures,interventionsOrProcedures,medicalActions]

# Set the regex to perform the substitution in array elements
array_regex: '^(\w+):(\d+)\.(\S+)'
