use strict;
use warnings;
use lib qw(lib app/engine/lib);
use Test::More;
use File::Temp qw(tempdir);
use Cwd qw(abs_path);
use Path::Tiny qw(path);
use Pheno::Ranker::Desktop::Terms;
use Pheno::Ranker::Desktop::Jobs;
my $temp = tempdir(CLEANUP => 1);
my $jobs = Pheno::Ranker::Desktop::Jobs->new(root => "$temp/jobs", worker => abs_path('app/engine/worker.pl'));
my $config = path($temp, 'config.yaml');
$config->spew_utf8("allowed_terms: [custom, diseases]\n");
my $input = path($temp, 'input.json');
$input->spew_utf8('[{"custom":1,"id":"a"},{"diseases":[],"other":true}]');
my $request = {config => $jobs->register_file("$config")->{id}, sources => [$jobs->register_file("$input")->{id}]};
my $choices = Pheno::Ranker::Desktop::Terms::choices($jobs, $request);
is_deeply($choices->{allowed}, [qw(custom diseases)], 'uses the selected configuration');
is_deeply($choices->{present}, [qw(custom diseases)], 'collects allowed entities across all previewed records');
is($choices->{note}, '', 'complete preview has no warning');
$input->spew_utf8('invalid json');
$choices = Pheno::Ranker::Desktop::Terms::choices($jobs, $request);
ok($choices->{note}, 'unreadable inputs explicitly report incomplete suggestions');
is_deeply($choices->{allowed}, [qw(custom diseases)], 'configured terms remain available');
ok(!eval { Pheno::Ranker::Desktop::Terms::choices($jobs, {sources => ['not-a-handle']}); 1 }, 'ungranted sources are rejected');
$jobs->shutdown;
done_testing;
