use strict;
use warnings;
use lib qw(lib app/engine/lib);
use Test::More;
use File::Temp qw(tempdir);
use Cwd qw(abs_path);
use Path::Tiny qw(path);
use JSON::XS;
use Pheno::Ranker::Desktop::Jobs;

my $root = tempdir(CLEANUP => 1);
my $jobs = Pheno::Ranker::Desktop::Jobs->new(root => $root, worker => abs_path('app/engine/worker.pl'));
my $id = 'a' x 40;
my $dir = path($root, $id);
$dir->child('staging')->mkpath;
my $status = {id=>$id,status=>'running',stages=>[{time=>1,message=>'Reading inputs'}]};
$dir->child('status.json')->spew_raw(encode_json($status));
$dir->child('staging','stdout.log')->spew_raw("\e[33mExample output\e[0m\n");
my $log = $jobs->log_preview($id);
like($log->{text},qr/Reading inputs/, 'stage history is available');
like($log->{text},qr/Example output/, 'live stdout is available');
unlike($log->{text},qr/\e/, 'terminal color escapes are removed');
ok(!$log->{truncated}, 'short output is complete');
$dir->child('staging','stderr.log')->spew_raw(('x' x 70000)."\nlatest error\n");
$log = $jobs->log_preview($id);
ok($log->{truncated}, 'large output is bounded');
like($log->{text},qr/latest error/, 'preview retains the tail');
ok(length($log->{text}) < 66000, 'does not load an unbounded log');
ok(!eval {$jobs->log_preview('../outside'); 1}, 'invalid run IDs rejected');
$dir->child('outputs')->mkpath;
my $file = $dir->child('outputs','stdout.log');
$file->spew_raw('Published output');
$status->{status}='completed';
$status->{directory}="".$dir->child('outputs');
$status->{result}={artifacts=>[{id=>'log',filename=>'stdout.log',bytes=>-s $file}]};
$dir->child('status.json')->spew_raw(encode_json($status));
like($jobs->log_preview($id)->{text},qr/Published output/, 'completed logs use validated output artifacts');
$status->{status}='failed';
$status->{message}='Operation failed';
$dir->child('status.json')->spew_raw(encode_json($status));
like($jobs->log_preview($id)->{text},qr/Operation failed/, 'failure diagnostic remains available');
done_testing;
