# Set the format
format: MXF

# Set the primary key for the objects
primary_key: title

# Set the allowed terms / properties
allowed_terms: [country,genre,year]

# Set the terms which are arrays
array_terms: [genre]

# Set the regex to perform the substitution in array elements
array_regex: '^(\w+):(\d+)'

# Set the path for array properties
id_correspondence:
  MXF:
    genre: genre
