---
# Set the number of cohort-patient comparison print to STDOUT
max_out: 50

# Set the key for sorting
sort_by: hamming

# Set the primary key for the objects
primary_key: title

# Set the allowed terms / properties
allowed_terms: [country,genre,year]
