---
# Set the maximum number of patient-cohort comparisons to be printed to STDOUT
max_out: 50

# Set the key to sort results in patient mode (hamming|jaccard)
sort_by: hamming

# Set the similarity metric to use in cohort mode (hamming|jaccard)
similarity_metric_cohort: hamming

# Set the primary key for the objects
primary_key: id

# Set the allowed terms or properties for use with include|exclude-terms
allowed_terms: [biosamples,diseases,ethnicity,exposures,files,geographicOrigin,id,info,interpretations,interventionsOrProcedures,karyotypicSex,measurements,measures,medicalActions,metaData,pedigrees,phenotypicFeatures,sex,subject,treatments]

# Set the limit on the maximum number of variables to be used; if exceeded, selection of variables will be random
max_number_var: 10000

# Set the seed number to initialize a pseudorandom number generator for max_number_var
seed: 123456789 

# Set the regex to exclude variables matching a specific pattern
exclude_properties_regex: 'info|notes|label|value|\.high|\.low|metaData|familyHistory|excluded|_visit|dateOfProcedure|files|reference\.id|reference\.description|timeObserved|dateOfBirth|timestamp|treatmentTarget|treatmentIntent|adverseEvents|treatmentTerminationReason'

# Set the terms which are arrays
array_terms: [biosamples,diseases,exposures,interpretations,interventionsOrProcedures,measures,measurements,medicalActions,phenotypicFeatures,treatments]

# Set the regex to identify array indexes, guiding their substitution within array elements
array_regex: '^(\w+):(\d+)\.(\S+)'

# Set the path to select values for substituting array indexes
id_correspondence:
  BFF:
    diseases: 'diseaseCode.id'
    exposures: 'exposureCode.id'
    interventionsOrProcedures: 'procedureCode.id'
    measures: 'assayCode.id'
    phenotypicFeatures: 'featureType.id'
    treatments: 'treatmentCode.id'
  PXF:
    phenotypicFeatures: 'type.id'
    measurements: 'assay.id'
    biosamples: 'id'
    interpretations: 'id'
    diseases: 'term.id'
    exposures: 'type.id'
    medicalActions: ['procedure.code.id','treatment.agent.id','radiationTherapy.modality.id','therapeuticRegimen.ontologyClass.id']
