---
# Set the number of cohort-patient comparison print to STDOUT
max_out: 50

# Set the key for sorting
sort_by: hamming

# Set the primary key for the objects
primary_key: id

# Set the allowed terms / properties
allowed_terms: [biosamples,diseases,ethnicity,exposures,files,geographicOrigin,id,info,interpretations,interventionsOrProcedures,karyotypicSex,measurements,measures,medicalActions,metaData,pedigrees,phenotypicFeatures,sex,subject,treatments]

# Set the maximum numbers to variables to be used (if more they will be randomized)
max_number_var: 10000

# Set the seed number to initialize a pseudorandom number generator for max_number_var:
seed: 123456789 

# Set the regex to discard variables that contain a given pattern
exclude_properties_regex: 'info|notes|label|value|\.high|\.low|metaData|familyHistory|excluded|_visit|dateOfProcedure|files|reference\.id|reference\.description|timeObserved|dateOfBirth|timestamp|treatmentTarget|treatmentIntent|adverseEvents|treatmentTerminationReason'

# Set the terms which are arrays
array_terms: [biosamples,diseases,exposures,interpretations,interventionsOrProcedures,measures,measurements,medicalActions,phenotypicFeatures,treatments]

# Set the regex to perform the substitution in array elements
array_regex: '^(\w+):(\d+)\.(\S+)'

# Set the path for array properties
id_correspondence:
  BFF:
    diseases: 'diseaseCode.id'
    exposures: 'exposureCode.id'
    interventionsOrProcedures: 'procedureCode.id'
    measures: 'assayCode.id'
    phenotypicFeatures: 'featureType.id'
    treatments: 'treatmentCode.id'
  PXF:
    phenotypicFeatures: 'type.id'
    measurements: 'assay.id'
    biosamples: 'id'
    interpretations: 'id'
    diseases: 'term.id'
    exposures: 'type.id'
    medicalActions: ['procedure.code.id','treatment.agent.id','radiationTherapy.modality.id','therapeuticRegimen.ontologyClass.id'] 
