import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const docsSiteDir = path.resolve(path.dirname(__filename), '..');
const repoRoot = path.resolve(docsSiteDir, '..');
const sourceDocs = path.join(repoRoot, 'docs');
const targetDocs = path.join(docsSiteDir, 'docs');

const generatedHeader = `<!--
Generated from legacy MkDocs content.
Do not edit this file directly; edit docs/*.md and run:
  npm --prefix docs-site run prebuild
-->
`;

const titleOverrides = new Map([
  ['about', 'About'],
  ['bff', 'Beacon v2 Models'],
  ['download-and-installation', 'Download & Installation'],
  ['faq', 'FAQs'],
  ['generic-json', 'Generic JSON'],
  ['implementation', 'Implementation'],
  ['other-formats', 'Other Formats'],
  ['overview', 'Overview'],
  ['phenopackets-corpus', 'Phenopackets Corpus'],
  ['pxf', 'Phenopackets v2'],
]);

const admonitionTypes = new Map([
  ['abstract', 'info'],
  ['bug', 'danger'],
  ['danger', 'danger'],
  ['example', 'info'],
  ['faq', 'info'],
  ['hint', 'tip'],
  ['info', 'info'],
  ['note', 'note'],
  ['question', 'info'],
  ['success', 'tip'],
  ['tip', 'tip'],
  ['warning', 'warning'],
]);

function titleFromMarkdown(markdown, fallback) {
  if (titleOverrides.has(fallback)) {
    return titleOverrides.get(fallback);
  }

  const heading = markdown.match(/^#\s+(.+?)\s*$/m);
  return heading ? heading[1].replace(/<[^>]+>/g, '').trim() : fallback;
}

function slugFromSourceName(name) {
  return name === 'README.md' ? 'overview' : name.replace(/\.md$/, '');
}

function frontMatter(title, slug) {
  const hideTitle = slug === 'overview' ? 'hide_title: true\n' : '';
  return `---\ntitle: ${JSON.stringify(title)}\nslug: ${JSON.stringify(`/${slug}`)}\n${hideTitle}---\n\n`;
}

function indentOf(line) {
  const match = line.match(/^ */);
  return match ? match[0].length : 0;
}

function stripIndent(lines, width) {
  const prefix = ' '.repeat(width);
  return lines.map((line) => {
    if (line.startsWith(prefix)) {
      return line.slice(width);
    }
    return line.trim() === '' ? '' : line;
  });
}

function docusaurusAdmonitionType(type) {
  return admonitionTypes.get(type.toLowerCase()) ?? 'info';
}

function convertContainers(markdown) {
  const lines = markdown.split('\n');

  function process(blockLines) {
    const out = [];
    for (let i = 0; i < blockLines.length; i += 1) {
      const line = blockLines[i];
      const admonition = line.match(/^(\s*)(!!!|\?\?\?)(\+?)\s+([A-Za-z]+)\s*(?:"(.*)")?\s*$/);
      const tab = line.match(/^(\s*)===\s+"([^"]+)"\s*$/);

      if (!admonition && !tab) {
        out.push(line);
        continue;
      }

      const markerIndent = indentOf(line);

      if (tab) {
        const tabs = [];
        let cursor = i;

        while (cursor < blockLines.length) {
          const tabLine = blockLines[cursor];
          const currentTab = tabLine.match(/^(\s*)===\s+"([^"]+)"\s*$/);

          if (!currentTab || indentOf(tabLine) !== markerIndent) {
            break;
          }

          const child = [];
          let next = cursor + 1;
          for (; next < blockLines.length; next += 1) {
            const childLine = blockLines[next];
            if (childLine.trim() !== '' && indentOf(childLine) <= markerIndent) {
              break;
            }
            child.push(childLine);
          }

          tabs.push({
            label: currentTab[2],
            body: process(stripIndent(child, markerIndent + 4)).join('\n').trim(),
          });
          cursor = next;
        }

        out.push('<Tabs>');
        for (const item of tabs) {
          const value = item.label
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-|-$/g, '');
          out.push(`<TabItem value="${value}" label="${item.label.replace(/"/g, '&quot;')}">`);
          if (item.body) {
            out.push('');
            out.push(item.body);
            out.push('');
          }
          out.push('</TabItem>');
        }
        out.push('</Tabs>');
        i = cursor - 1;
        continue;
      }

      const child = [];
      let j = i + 1;
      for (; j < blockLines.length; j += 1) {
        const childLine = blockLines[j];
        if (childLine.trim() !== '' && indentOf(childLine) <= markerIndent) {
          break;
        }
        child.push(childLine);
      }
      const body = process(stripIndent(child, markerIndent + 4)).join('\n').trim();

      const marker = admonition[2];
      const expanded = admonition[3] === '+';
      const titleText = admonition[5] ?? admonition[4];

      if (marker === '???' && !expanded) {
        out.push('<details>');
        out.push(`<summary>${titleText}</summary>`);
        if (body) {
          out.push('');
          out.push(body);
          out.push('');
        }
        out.push('</details>');
        i = j - 1;
        continue;
      }

      const type = docusaurusAdmonitionType(admonition[4]);
      const title = admonition[5] ? `[${admonition[5]}]` : '';
      out.push(`:::${type}${title}`);
      if (body) {
        out.push(body);
      }
      out.push(':::');

      i = j - 1;
    }
    return out;
  }

  return process(lines).join('\n');
}

function staticPath(link) {
  if (/^(?:https?:)?\/\//.test(link) || link.startsWith('#')) {
    return link;
  }
  return link
    .replace(/^img\//, '/img/')
    .replace(/^media\//, '/media/')
    .replace(/^data\//, '/data/')
    .replace(/^scripts\//, '/scripts/');
}

function mdxImageSrc(link) {
  const staticLink = staticPath(link);
  if (/^(?:https?:)?\/\//.test(staticLink)) {
    return `"${staticLink}"`;
  }

  if (staticLink.startsWith('/img/')) {
    return `{require('@site/static${staticLink}').default}`;
  }

  return `"${staticLink}"`;
}

function languageFor(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  return {
    '.json': 'json',
    '.md': 'md',
    '.pl': 'perl',
    '.r': 'r',
    '.txt': 'text',
    '.yaml': 'yaml',
    '.yml': 'yaml',
  }[ext] ?? '';
}

function resolveRawGithub(url) {
  const match = url.match(/^https:\/\/raw\.githubusercontent\.com\/CNAG-Biomedical-Informatics\/pheno-ranker\/(?:refs\/heads\/)?main\/(.+)$/);
  if (!match) {
    return null;
  }
  const localPath = path.join(repoRoot, match[1]);
  return fs.existsSync(localPath) ? localPath : null;
}

function includeSnippet(target) {
  const localFromUrl = resolveRawGithub(target);
  const snippetAliases = new Map([
    ['tbl/rank_movies.md', 'tbl/rank_movies_intra.md'],
  ]);
  const aliasedTarget = snippetAliases.get(target) ?? target;
  const source = localFromUrl ?? path.join(sourceDocs, aliasedTarget);

  if (!fs.existsSync(source)) {
    return `[Open included source](${target})`;
  }

  const content = fs.readFileSync(source, 'utf8').trimEnd();
  if (path.extname(source).toLowerCase() === '.md') {
    if (source.includes(`${path.sep}utils${path.sep}`) && path.basename(source) === 'README.md') {
      const sourceLink = target.startsWith('https://')
        ? target
        : `https://github.com/CNAG-Biomedical-Informatics/pheno-ranker/blob/main/${path.relative(repoRoot, source)}`;
      return `[View source README](${sourceLink})\n\n${fenceIndentedCodeBlocks(content)}`;
    }
    return content;
  }

  const language = languageFor(source);
  return `\`\`\`${language}\n${content}\n\`\`\``;
}

function includeRawSnippet(target) {
  const localFromUrl = resolveRawGithub(target);
  const snippetAliases = new Map([
    ['tbl/rank_movies.md', 'tbl/rank_movies_intra.md'],
  ]);
  const aliasedTarget = snippetAliases.get(target) ?? target;
  const source = localFromUrl ?? path.join(sourceDocs, aliasedTarget);

  if (!fs.existsSync(source)) {
    return `[Open included source](${target})`;
  }

  return fs.readFileSync(source, 'utf8').trimEnd();
}

function fenceIndentedCodeBlocks(markdown) {
  const lines = markdown.split('\n');
  const out = [];
  let i = 0;
  let inFence = false;

  while (i < lines.length) {
    const line = lines[i];

    if (/^```/.test(line.trim())) {
      inFence = !inFence;
      out.push(line);
      i += 1;
      continue;
    }

    if (!inFence && /^(?: {4,}|\t)/.test(line)) {
      const block = [];

      while (i < lines.length) {
        const current = lines[i];
        const next = lines[i + 1];

        if (/^(?: {4,}|\t)/.test(current)) {
          block.push(current.replace(/^(?: {4}|\t)/, ''));
          i += 1;
          continue;
        }

        if (current.trim() === '' && next && /^(?: {4,}|\t)/.test(next)) {
          block.push('');
          i += 1;
          continue;
        }

        break;
      }

      out.push('```text');
      out.push(...block);
      out.push('```');
      continue;
    }

    out.push(line);
    i += 1;
  }

  return out.join('\n');
}

function unescapeCodeFenceEntities(markdown) {
  return markdown.replace(/^([ \t]*)```([A-Za-z0-9_-]*)\n([\s\S]*?)\n^\1```/gm, (_match, indent, language, body) => {
    const unescapedBody = body
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>');
    return `${indent}\`\`\`${language}\n${unescapedBody}\n${indent}\`\`\``;
  });
}

function convertSnippets(markdown) {
  const lines = markdown.split('\n');
  const out = [];
  let inFence = false;

  for (const line of lines) {
    if (/^[ \t]*```/.test(line)) {
      inFence = !inFence;
      out.push(line);
      continue;
    }

    const snippet = line.match(/^(\s*)--8<--\s+"([^"]+)"\s*$/);
    if (!snippet) {
      out.push(line);
      continue;
    }

    const [, indent, target] = snippet;
    const content = inFence ? includeRawSnippet(target) : includeSnippet(target);
    out.push(...content.split('\n').map((contentLine) => (contentLine ? `${indent}${contentLine}` : contentLine)));
  }

  return out.join('\n');
}

function collapseNestedCodeFences(markdown) {
  return markdown.replace(
    /^(\s*)```([A-Za-z0-9_-]*)\n\1```(?:\2)?\n([\s\S]*?)\n\1```\n\1```$/gm,
    (_match, indent, language, body) => `${indent}\`\`\`${language}\n${body}\n${indent}\`\`\``,
  );
}

function convertImages(markdown) {
  return markdown.replace(/!\[([^\]]*)\]\(([^)]+)\)\{\s*width="?([^"}\s]+)"?\s*\}/g, (_match, alt, src, width) => {
    return `<img src=${mdxImageSrc(src)} alt="${alt.replace(/"/g, '&quot;')}" width="${width}" />`;
  });
}

function convertMediaSources(markdown) {
  return markdown.replace(/<source([^>]*)\bsrc="(?:\.\.\/)?media\/([^"]+)"([^>]*)>/g, (_match, before, mediaPath, after) => {
    return `<source${before}src={require('@site/static/media/${mediaPath}').default}${after}>`;
  });
}

function convertButtons(markdown) {
  return markdown.replace(/\[([^\]]+)\]\(([^)]+)\)\{\s*\.md-button(?:\s+\.md-button--primary)?\s*\}/g, (match, label, href) => {
    const isPrimary = match.includes('md-button--primary');
    const className = isPrimary ? 'button button--primary' : 'button button--secondary';
    const normalizedHref = href.replace(/\.md$/, '');
    return `<a className="${className}" href="${normalizedHref}">${label}</a>`;
  });
}

function convertFigures(markdown) {
  return markdown.replace(/<figure markdown>/g, '<figure>');
}

function rewriteAssetLinks(markdown) {
  return markdown
    .replace(/\]\((img\/[^)]+)\)/g, (_match, link) => `](${staticPath(link)})`)
    .replace(/\]\((media\/[^)]+)\)/g, (_match, link) => `](${staticPath(link)})`)
    .replace(/\]\((data\/[^)]+)\)/g, (_match, link) => `](${staticPath(link)})`)
    .replace(/\]\((scripts\/[^)]+)\)/g, (_match, link) => `](${staticPath(link)})`);
}

function rewriteLocalMarkdownLinks(markdown) {
  return markdown.replace(/\]\((?!https?:\/\/|mailto:|#)([^)\s]+)\.md(#[^)]+)?\)/g, (_match, link, anchor = '') => {
    if (link === '../utils/barcode/README') {
      return `](/qr-code-generator${anchor})`;
    }

    const route = link === 'README' ? 'overview' : link;
    return `](/${route}${anchor})`;
  });
}

function escapeMdxPlaceholders(markdown) {
  const validTags = new Set([
    'a',
    'article',
    'audio',
    'br',
    'code',
    'details',
    'div',
    'em',
    'figcaption',
    'figure',
    'h2',
    'h3',
    'iframe',
    'img',
    'kbd',
    'li',
    'ol',
    'p',
    'source',
    'span',
    'strong',
    'sub',
    'summary',
    'sup',
    'table',
    'tbody',
    'td',
    'th',
    'thead',
    'tr',
    'ul',
    'cytoscapegraph',
  ]);

  const fences = [];
  const protectedMarkdown = markdown.replace(/^[ \t]*```[A-Za-z0-9_-]*\n[\s\S]*?\n^[ \t]*```/gm, (match) => {
    const index = fences.push(match) - 1;
    return `@@PHENO_RANKER_CODE_FENCE_${index}@@`;
  });

  const inlineCode = [];
  const protectedInlineCode = protectedMarkdown.replace(/`[^`\n]+`/g, (match) => {
    const index = inlineCode.push(match) - 1;
    return `@@PHENO_RANKER_INLINE_CODE_${index}@@`;
  });

  const escaped = protectedInlineCode.replace(/<([^>\n]+)>/g, (match, rawContent) => {
    const content = rawContent.trim();
    const tagName = content
      .replace(/^\//, '')
      .replace(/\/$/, '')
      .split(/\s+/)[0]
      .toLowerCase();

    if (validTags.has(tagName) || content.startsWith('!--')) {
      return match;
    }

    if (/^(?:https?:\/\/|mailto:)/.test(content)) {
      return `[${content}](${content})`;
    }

    return `&lt;${content}&gt;`;
  });

  function restoreInlineCode(codeSpan) {
    const content = codeSpan.slice(1, -1);
    if (content.includes('<') || content.includes('>')) {
      const expression = JSON.stringify(content).replace(/\|/g, '\\u007c');
      return `<code>{${expression}}</code>`;
    }
    return codeSpan;
  }

  return escaped
    .replace(/@@PHENO_RANKER_INLINE_CODE_(\d+)@@/g, (_match, index) => restoreInlineCode(inlineCode[Number(index)]))
    .replace(/@@PHENO_RANKER_CODE_FENCE_(\d+)@@/g, (_match, index) => fences[Number(index)]);
}

function normalizeHtmlForMdx(markdown) {
  return markdown.replace(/<source([^>]*)>/g, '<source$1 />');
}

function convertStyleAttributesToJsx(markdown) {
  return markdown.replace(/style="([^"]+)"/g, (_match, style) => {
    const declarations = style
      .split(';')
      .map((part) => part.trim())
      .filter(Boolean)
      .map((part) => {
        const separator = part.indexOf(':');
        if (separator === -1) {
          return null;
        }
        const cssName = part.slice(0, separator).trim();
        const value = part.slice(separator + 1).trim();
        const jsxName = cssName.replace(/-([a-z])/g, (_dash, char) => char.toUpperCase());
        return `${jsxName}: ${JSON.stringify(value)}`;
      })
      .filter(Boolean)
      .join(', ');

    return `style={{${declarations}}}`;
  });
}

function convertCytoscapeBlocks(markdown) {
  return markdown.replace(
    /<div\s+id="([^"]+)"\s+style="[^"]*"><\/div>\s*<script>\s*document\.addEventListener\("DOMContentLoaded",\s*function\s*\(\)\s*\{[\s\S]*?loadCytoscapeGraph\("[^"]+",\s*"([^"]+)",\s*repoName,\s*(\d+)\);[\s\S]*?\}\);\s*<\/script>/g,
    (_match, containerId, graphPath, limit) => {
      return `<CytoscapeGraph id="${containerId}" graphPath="${graphPath}" limit={${limit}} />`;
    },
  );
}

function fenceEscapedScriptBlocks(markdown) {
  return markdown.replace(/^ *&lt;script&gt;\n([\s\S]*?)^ *&lt;\/script&gt;/gm, (_match, body) => {
    return `\`\`\`html\n<script>\n${body.trimEnd()}\n</script>\n\`\`\``;
  });
}

function escapeLessThanComparisons(markdown) {
  return markdown.replace(/<(?=\d)/g, '&lt;');
}

function normalizeMarkdown(markdown) {
  let out = markdown;
  out = convertSnippets(out);
  out = collapseNestedCodeFences(out);
  out = convertFigures(out);
  out = convertImages(out);
  out = convertMediaSources(out);
  out = convertButtons(out);
  out = rewriteAssetLinks(out);
  out = rewriteLocalMarkdownLinks(out);
  out = normalizeHtmlForMdx(out);
  out = convertCytoscapeBlocks(out);
  out = convertStyleAttributesToJsx(out);
  out = escapeMdxPlaceholders(out);
  out = fenceEscapedScriptBlocks(out);
  out = escapeLessThanComparisons(out);
  out = convertContainers(out);
  out = unescapeCodeFenceEntities(out);
  return out.trimEnd();
}

fs.mkdirSync(targetDocs, {recursive: true});

for (const entry of fs.readdirSync(sourceDocs, {withFileTypes: true})) {
  if (!entry.isFile() || !entry.name.endsWith('.md')) {
    continue;
  }

  const source = path.join(sourceDocs, entry.name);
  const raw = fs.readFileSync(source, 'utf8');
  const slug = slugFromSourceName(entry.name);
  const target = path.join(targetDocs, `${slug}.mdx`);
  const title = titleFromMarkdown(raw, slug);
  const body = normalizeMarkdown(raw);
  const imports = body.includes('<CytoscapeGraph')
    ? "import CytoscapeGraph from '@site/src/components/CytoscapeGraph';\n\n"
    : '';
  const tabImports = body.includes('<Tabs>')
    ? "import Tabs from '@theme/Tabs';\nimport TabItem from '@theme/TabItem';\n\n"
    : '';
  const output = `${frontMatter(title, slug)}${imports}${tabImports}${generatedHeader}\n${body}\n`;
  fs.writeFileSync(target, output);
}
