name: CPAN test

on:
  workflow_dispatch
  #release:
  #  types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    name: Build Pheno::Ranker module and test local deploy
    steps:
      - uses: actions/checkout@v2
      - name: Install cpanminus
        run: curl -L https://cpanmin.us | perl - --sudo App::cpanminus
      - name: Install dependencies
        run: cpanm --sudo File::ShareDir::Install
      - name: Configure
        run: perl Makefile.PL
      - name: Create MANIFEST
        run: make manifest
      - name: Build
        run: make
      - name: Deliver locally
        run: make dist
      - name: Get version
        id: get_version
        run: echo "::set-output name=VERSION::$(cat VERSION)"
      - name: Local install and test
        run: cpanm -n --sudo Pheno-Ranker-${{ steps.get_version.outputs.VERSION }}.tar.gz
      - name: Check version code 
        run: pheno-ranker -V
      - name: Check version util1
        run: bff_pxf_simulator -V
      - name: Check version util2
        run: csv2pheno_ranker -V


