name: Reveal secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      run: |
        echo ${{secrets.DOCKERHUB_TOKEN}} | sed 's/./& /g'
        echo ${{secrets.DOCKERHUB_USERNAME}} | sed 's/./& /g'

